#!/usr/bin/env python

from optparse import OptionParser
import paramiko
import os
from path import path
import json

usage = "usage: %prog [options] arg"
parser = OptionParser(usage)
parser.add_option('-d', '--deploy-microsites', dest='config_filename', help='transfers over directories of .html files to another server according to CONFIG_FILENAME')

(options, args) = parser.parse_args()

if options.config_filename:

    with open(options.config_filename) as config_file:
        config = json.load(config_file)

    for correlator in config['correlators']:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(correlator['host'], username=correlator['userName'], key_filename=correlator['keyFileName'])
        sftp = ssh.open_sftp()

        local_dir = path(config['inputsDir'] + '/' + correlator['site'])
        for local_file_name in local_dir.files(pattern='*.html'):
            head, tail = os.path.split(local_file_name)
            remote_file_name = correlator['destDir'] + '/' + tail
            sftp.put(local_file_name, remote_file_name)  # overwrites remote file

        sftp.close()
        ssh.close()